"""initial schema

Revision ID: 5f1c8989095e
Revises: 
Create Date: 2026-05-23 19:11:05.698436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f1c8989095e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('xp_bonus', sa.Integer(), nullable=True),
    sa.Column('rarity', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('avatar', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.String(length=300), nullable=True),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.Column('global_level', sa.Integer(), nullable=False),
    sa.Column('total_quests_completed', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_active_date', sa.Date(), nullable=True),
    sa.Column('streak_penalty_enabled', sa.Boolean(), nullable=True),
    sa.Column('theme', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('daily_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=True),
    sa.Column('quests_completed', sa.Integer(), nullable=True),
    sa.Column('quests_failed', sa.Integer(), nullable=True),
    sa.Column('skills_active', sa.Integer(), nullable=True),
    sa.Column('streak_day', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_daily_stat_user_date')
    )
    with op.batch_alter_table('daily_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_stats_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_stats_user_id'), ['user_id'], unique=False)

    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('current_xp', sa.Integer(), nullable=False),
    sa.Column('current_level', sa.Integer(), nullable=False),
    sa.Column('total_xp_earned', sa.Integer(), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('total_quests_completed', sa.Integer(), nullable=False),
    sa.Column('total_quests_failed', sa.Integer(), nullable=False),
    sa.Column('last_quest_date', sa.Date(), nullable=True),
    sa.Column('decay_enabled', sa.Boolean(), nullable=True),
    sa.Column('last_decay_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_user_id'), ['user_id'], unique=False)

    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_user_achievement')
    )
    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_achievements_user_id'), ['user_id'], unique=False)

    op.create_table('side_quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('estimated_duration', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('recurrence_type', sa.String(length=20), nullable=True),
    sa.Column('recurrence_days', sa.String(length=50), nullable=True),
    sa.Column('is_boss_battle', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('xp_multiplier', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('side_quests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_side_quests_skill_id'), ['skill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_side_quests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_side_quests_user_id'), ['user_id'], unique=False)

    op.create_table('streak_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('streak_count', sa.Integer(), nullable=False),
    sa.Column('quests_completed', sa.Integer(), nullable=True),
    sa.Column('xp_earned', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill_id', 'date', name='uq_streak_user_skill_date')
    )
    with op.batch_alter_table('streak_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_streak_logs_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_streak_logs_skill_id'), ['skill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_streak_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_streak_user_date', ['user_id', 'date'], unique=False)

    op.create_table('xp_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('quest_id', sa.Integer(), nullable=True),
    sa.Column('xp_amount', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('level_before', sa.Integer(), nullable=False),
    sa.Column('level_after', sa.Integer(), nullable=False),
    sa.Column('leveled_up', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quest_id'], ['side_quests.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('xp_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_xp_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_xp_logs_skill_id'), ['skill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_xp_logs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('xp_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_xp_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_xp_logs_skill_id'))
        batch_op.drop_index(batch_op.f('ix_xp_logs_created_at'))

    op.drop_table('xp_logs')
    with op.batch_alter_table('streak_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_streak_user_date')
        batch_op.drop_index(batch_op.f('ix_streak_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_streak_logs_skill_id'))
        batch_op.drop_index(batch_op.f('ix_streak_logs_date'))

    op.drop_table('streak_logs')
    with op.batch_alter_table('side_quests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_side_quests_user_id'))
        batch_op.drop_index(batch_op.f('ix_side_quests_status'))
        batch_op.drop_index(batch_op.f('ix_side_quests_skill_id'))

    op.drop_table('side_quests')
    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_achievements_user_id'))

    op.drop_table('user_achievements')
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_user_id'))

    op.drop_table('skills')
    with op.batch_alter_table('daily_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_stats_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_stats_date'))

    op.drop_table('daily_stats')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('achievements')
    # ### end Alembic commands ###
